[package]
name = "portping"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.37", features = ["full"] }
ctable = { git = "https://github.com/dcopenhaver/ctable-rs" }
